### ISSUE TITLE
Whitelist not applied to API files

### ISSUE THREAD

**Issue by mainhanu** [cdnjs/api-server#10]
for example

https://cdnjs.com/libraries/antd
https://api.cdnjs.com/libraries/antd

for version 4.0.2 and 4.0.1, API list has extra files like `antd.dark.less `, which is 403

![image](https://user-images.githubusercontent.com/48398913/76302973-e49c8e00-62fb-11ea-8b2c-017697576633.png)

how to get real file list from API?

**Comment by MattIPv4** [comment]
Resolved in https://github.com/cdnjs/api-server/commit/eff3047fa42550c0c98332fee88b7570ae34484e
