### ISSUE TITLE
API Search Results Issue

### ISSUE THREAD

**Issue by Tantumonium** [cdnjs/api-server#13]
Searching for "jqueryui" using the following string, not only is "jqueryui" is NOT displayed in the results, neither are any other libraries where "jqueryui" or "jQuery UI" are included as either keywords/tags or are used in the library's description.

`https://api.cdnjs.com/libraries?search=jqueryui&output=human&fields=filename,homepage,version,keywords,description`

Whereas by removing "description" from the "fields" list, and searching for "jqueryui" using the following string, "jqueryui" IS displayed in the results... as are all the other libraries where "jqueryui" or "jQuery UI" are mentioned.

`https://api.cdnjs.com/libraries?search=jqueryui&output=human&fields=filename,homepage,version,keywords`

**Comment by Tantumonium** [comment]
I appreciate you looking into it and for the explanation.

In case anyone else is interested... I ended up adding the following filter to my AJAX call... which cleans things up nicely.

`if ( ( obj.name ).toLowerCase().indexOf( search.term ) >= 0 || ( obj.description ).toLowerCase().indexOf( search.term ) >= 0 ) { return obj; }`

**Comment by MattIPv4** [comment]
I realise I didn't actually respond to your comments:

> Are you currently using the Algolia attributesToRetrieve browseparameter to handle your fields=filename,homepage,version,keywords parameter?

We request all fields from Algolia and filter ourselves so that we can return null for extra fields requests & inject our own custom ones.

> If so, could restrictSearchableAttributes be added to a future release?

I think that seems sensible to add, perhaps as a `search_fields` query param? What do you think?

**Comment by Tantumonium** [comment]
> I think that seems sensible to add, perhaps as a search_fields query param? What do you think?

I think that would make an excellent addition to the CDNJS API. :)

**Comment by MattIPv4** [comment]
I've added this in https://github.com/cdnjs/api-server/commit/8358610ddbe19e2bf4dc3a071d9c49c82ceb1a01, though this hasn't been deployed yet and the new API server is only handling 50% of traffic, so I'm unsure when this will really be available for use.

**Comment by MattIPv4** [comment]
This is now in production at 100% traffic.
