### ISSUE TITLE
Document API Worker

### ISSUE THREAD

**Issue by tc80** [cdnjs/api-server#35]
Idea: Maybe we can make a markdown file in this repo explaining the endpoints of the worker. 

I can redirect http://metadata.speedcdnjs.com and http://metadata.speedcdnjs.com/help to that page.

**Comment by MattIPv4** [comment]
Imo, we should probably keep it undocuemented to reduce the chances that folks become reliant on it. The app will (#32) have all the endpoints "documented" through methods, I don't think we should go further.

**Comment by tc80** [comment]
sgtm!
