### ISSUE TITLE
Invalid JSON for jquery-validate package

### ISSUE THREAD

**Issue by vladdy-moses** [cdnjs/api-server#48]
## Details

There is invalid JSON at https://api.cdnjs.com/libraries/jquery-validate (see end of the document):

```
...
"sri":{"additional-methods.js":"sha512-5PDORojuUAKi3sd4xcqVI+ZtPs9QT6lPHG5LbwrqWlTFwK22Bewya3IVObPvaUFX6DUXUVvE1qABX4U0mU09mQ==","additional-methods.min.js":"sha512-Pk8WfSRH6frVrOJMzqDcDTVDDBeHvGZEDtEiULZdTOuumP/vz5QxuHSE1lisKdocrCs2e8F4IAjkDjZR/HFSzA==","jquery.validate.js":"sha512-F41aKGb1IjCLJVsV8Gcz+FTp2r6iUGTanYIyxbE8Nasq4dYDgv4l39sL7bpyL2J3LiHgWii0zzG9IsGY+4vMjw==","jquery.validate.min.js":"sha512-mnn/B8z6KVHa04hFn5hT0kLAn/j/0z4Ir3Kj41vvMosigCq1stpfiAF7lgPcKv/ua9dJXcJthXN5eMTJKzs2Dg==","localization/messages_ar.js":"sha512-U+6AxJtnHBTCrIeBLoqFswvn1dZbWGkGrSK17fW3qv0KLouZ/dz5U4wl8oGyGC048VSKOjLooi27BaiolIN82A==","localization/messages_ar.min.js":"sha512-XpuXsmAxK0Z49EebDHTnwLmOfsKwc04dhopPI0C5u5VDza41UF/zpT/Bg4/2qnTwOTFx6Crhxz5AVi5AHtEBnw==","localization/messages_bg.js":"sha512-R3Kl0eqlqHkIffFAtW0ylMFI0V/sab35/V3oEUai7ESTyPr65OGy0jvtFrN2/gLQFXGz7MniiuxsyDSiQyMiNg==","localization/messages_bg.min.js":"sha512-EVHsVjXaylvI7jeqix89I6ncSqUeJaqHJkfk0lr4lQSFSp4jMxcrFqmKsnqj4GapkzwFGcCHcu5nY63KDNIwsw==","localization/messages_ca.js":"sha512-wh+/iv0LwUZgPPH8A5mB+JosQufF9YGl9vcmDtOYhMWIAARWbnnI1xRWI90FzbPT3Fm6dtIJG09/2GPn4Ao6lw==","localization/messages_ca.min.js":"sha512-HoCsVwZTE3eVMmE4dedFnuUILGZgKGuwIske7lC7qC4mhlLJeckCjVNgeIoPcj3zpwbA+r3BVRJOipbk0sim1Q==","localization/messages_cn.js":"sha512-GFtoKnPo5dQcOkc0alESIgSVE8sHmzbs1E7jO3H8Uc
```

For [jquery](https://api.cdnjs.com/libraries/jquery) the JSON-output is valid.

### Description

We used libman (by Microsoft) for getting frontend packages from cdnjs for our web app.
But 2 days ago error LIB002 was happen.
We analyze this problem and detect broken JSON from cdnjs api server.

### Steps to reproduce

1. Go to https://api.cdnjs.com/libraries/jquery-validate (`curl https://api.cdnjs.com/libraries/jquery-validate`)
2. Parse JSON
3. Get deserialization error

### Expected behavior

1. JSON shoud be valid :)

### Logs

[jquery-validate.json.txt](https://github.com/cdnjs/api-server/files/6537614/jquery-validate.json.txt)

**Comment by MattIPv4** [comment]
👋 Thanks for the report -- our team are actively looking into this! We'll keep the status page updated best we can: https://status.cdnjs.com/incidents/39sjf0gvcd8s

**Comment by MattIPv4** [comment]
This should now be resolved :)

**Comment by vladdy-moses** [comment]
Unfortunately not :(

I made `curl -H 'Cache-Control: no-cache' https://api.cdnjs.com/libraries/jquery-validate --trace-asci output.txt`.
[output.txt](https://github.com/cdnjs/api-server/files/6543832/output.txt)

**Comment by MattIPv4** [comment]
@vladdy-moses I'm unable produce this, as our automated tests -- If I run `curl -H 'Cache-Control: no-cache' https://api.cdnjs.com/libraries/jquery-validate\?_\=$(date +%s) | jq` the response is valid JSON

If you run the above, which uses a query param to ensure you're getting a fresh response, what do you get back?
