### ISSUE TITLE
Package info not update

### ISSUE THREAD

**Issue by edwardfxiao** [cdnjs/api-server#70]
### Description
The fields ```homepage``` and ```description``` of my package on [cdnjs.com](https://cdnjs.com/libraries/react-inputs-validation) has not been updated after https://github.com/cdnjs/packages/pull/1112 has merged.

### Steps to reproduce

- I request a PR to update ```homepage```, ```description```, and ```repository url ```  in ```cdnjs/packages``` https://github.com/cdnjs/packages/pull/1112

- I also published a new version of ```4.9.2``` trying to trigger the update

### Expected behavior

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/11728228/164822362-576d361d-4e04-4202-afb4-269e3df9eb4c.png">

### Logs
- ```cdnjs/logs``` shows the new info has been update in to the kv store
https://github.com/cdnjs/logs/commit/b061c3c090eb6f9213a76d463599497cdf06d5c9

- However, https://api.cdnjs.com/libraries/react-inputs-validation shows the outdated information

**Comment by edwardfxiao** [comment]
Forgot to mention, the update is all because my GitHub username has changed to ```edwardfxiao``` from ```edwardfhsiao```

**Comment by MattIPv4** [comment]
👋 Looks like this might have been a caching issue, as I see the updated values now:
![image](https://user-images.githubusercontent.com/12371363/181661729-389dcae3-c5cd-40a9-98a0-65df29a8d950.png)
