### ISSUE TITLE
The fileType field could not be obtained

### ISSUE THREAD

**Issue by zmcode** [cdnjs/api-server#86]
https://api.cdnjs.com/libraries?fields=version,fileType

This gets the fileType null

How to obtain ?

https://user-images.githubusercontent.com/48686959/210209757-dbfe5293-284a-4a86-9b1d-f7bf02b8e240.png
The document says to pass the fileType field, but returns null

**Comment by MattIPv4** [comment]
👋 This should now be working:

```
curl -sSL api.cdnjs.com/libraries\?fields=fileType | jq -r .results\[0].fileType
js
```
